default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['SQL_USERNAME'] %>
  password: <%= ENV['SQL_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: pfv_dev

test:
  <<: *default
  database: pfv_test

production:
  <<: *default
  database: pfv_product